home/urls.py
from django.urls import path
from . import views
from . models import FavBooks
from django.conf import settings
from django.conf.urls.static import static
app_name='home'
urlpatterns=[
    path('',views.HomeView,name='home'),
    path('addBooks/',views.addBooks,name='addBooks'),
    path('uploadpic/',views.uploadPic,name='uploadPic'),
    path('myBooks/',views.BooksView.as_view(),name='myBooks'),
    path('<int:pk>/', views.BookDetailsView.as_view(), name='myBooks'),
    path('<int:pk>/userbooks/', views.UsersBooksView, name='userBooks'),
    path('search/', views.SearchedBooks, name='searchedBooks'),
    path('favoriteAjax/', views.favorite_ajax, name='favoriteAjax'),
    path('removefavoriteAjax/', views.removefavorite_ajax, name='removefavoriteAjax'),
    path('wishList/',views.WishlistView.as_view(),name='wishList'),
    path('deletebook/', views.deleteBook, name='deleteBook'),
    ]

swapit/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include("django.contrib.auth.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
class UserBooks(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    username = models.CharField(max_length=200)
    book_name = models.CharField(max_length=200)
    book_author = models.CharField(max_length=200)
    book_ISBN=models.CharField(max_length=200)
    book_genre = models.CharField(max_length=200)
    book_status=models.BooleanField(default=False)
    book_url=models.URLField(max_length=128)
    book_rating = models.IntegerField(default=0)
    def __str__(self):
        return self.book_name
class FavBooks(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    book_id= models.ForeignKey(UserBooks,on_delete=models.CASCADE,null=True)
    class Meta:
        unique_together = (("user_id", "book_id"),)


class BooksIsbn(models.Model):
    book_ISBN = models.CharField(max_length=100,unique=True)
    count = models.IntegerField()

class Images(models.Model):
    user_id=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    image=models.FileField()

home/forms.py
from django import forms
from . models import UserBooks,Images
from django.contrib.auth.models import User
class BookForm(forms.ModelForm):
    class Meta:
        model = UserBooks
        fields=['book_name','book_author','book_ISBN','book_genre','book_url']

class ImageUploadForm(forms.ModelForm):
     class Meta:
         model=Images
         fields=['image']

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic.edit import FormView
from . forms import BookForm,ImageUploadForm
from django.contrib.auth.models import User
from . models import UserBooks
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import UserBooks,FavBooks,BooksIsbn,Images
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from bokeh.io import output_file,show,output_notebook,push_notebook
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource,HoverTool,CategoricalColorMapper
from bokeh.layouts import row,column,gridplot
from bokeh.models.widgets import Tabs,Panel
from bokeh.embed import components
from bokeh.resources import CDN
from bokeh.models import CustomJS, ColumnDataSource, HoverTool
from math import pi
import csv
@login_required
def HomeView(request):
    flag = Images.objects.filter(user_id=request.user).exists()
    topbooks = UserBooks.objects.order_by('-book_rating')[:5]
    obj=0
    if (flag):
        obj = Images.objects.get(user_id=request.user)
    hover_tool = HoverTool()
    p = figure(x_axis_label='Rating', y_axis_label='No.Of.Books', plot_width=400, plot_height=250,tools=[hover_tool, "crosshair,pan,reset"])
    bookgenres = UserBooks.objects.order_by('book_genre').values('book_genre').distinct()
    user = User.objects.get(pk=request.user.id)
    gen = set()
    userbooks = user.userbooks_set.all()
    for books in userbooks:
        gen.add(books.book_genre)
    gen = list(gen)
    result = []
    for temp in gen:
        result.append(user.userbooks_set.filter(book_genre=temp).count())
    hover_tool = HoverTool()
    p1 = figure(x_axis_label='Genre', y_axis_label='No.Of.Books', x_range=gen, plot_width=400, plot_height=250,
               tools=[hover_tool, "crosshair,pan,reset"])
    p1.vbar(x=gen, top=result, width=0.5, color='navy', alpha=0.75)
    p1.xaxis.major_label_orientation = pi / 4
    script1, div1 = components(p1)
    if(request.method=='POST'):
        str=request.POST['topbook']
        result=[]
        for i in range(1, 11):
            result.append(UserBooks.objects.filter(book_genre=str).filter(book_rating=i).count())
        topbooks=UserBooks.objects.filter(book_genre__contains=str).order_by('-book_rating')[:5]
        p.vbar(x=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], top=result, width=0.5, color='navy', alpha=0.75)
        script,div=components(p)
        genre=str
        return render(request, 'home/homepage.html',{'flag': flag, 'obj': obj, 'topbooks': topbooks, 'bookgenres': bookgenres,'script':script,'div':div,'script1':script1,'div1':div1,'genre':genre})

    return render(request, 'home/homepage.html',{'flag': flag, 'obj': obj, 'topbooks': topbooks, 'bookgenres': bookgenres,'script1':script1,'div1':div1})

class BookDetailsView (LoginRequiredMixin,generic.DetailView):
    model=UserBooks
    template_name='home/bookdetails.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = self.request.user.userbooks_set.all
        context['favorites']=self.request.user.favbooks_set.all
        context['flag']=True
        context['popular']=UserBooks.objects.filter(book_genre=super().get_object().book_genre).order_by('-book_rating')[:5]
        return context


class BooksView (LoginRequiredMixin,generic.DetailView):
     model=User
     template_name='home/mybooks.html'

     def get_object(self):
         return self.request.user

class WishlistView (LoginRequiredMixin,generic.DetailView):
    model=User
    template_name='home/wishlist.html'

    def get_object(self):
         return self.request.user

@login_required
def SearchedBooks(request):
   if(request.method=='GET'):
       item=request.GET['q']
       flag=request.GET['NAME']
       if(flag=='1'):
           setvalues=UserBooks.objects.filter(book_name__contains=item)
           return render(request,'home/search.html',{'setvalues':setvalues,'flag':1})
       if (flag == '2'):
           setvalues = User.objects.filter(username__contains=item)
           return render(request, 'home/search.html', {'setvalues': setvalues, 'flag': 2})
       if (flag == '3'):
           setvalues = UserBooks.objects.filter(book_ISBN__contains=item)
           return render(request, 'home/search.html', {'setvalues': setvalues, 'flag': 3})
       if (flag == '4'):
           setvalues = UserBooks.objects.filter(book_author__contains=item)
           return render(request, 'home/search.html', {'setvalues': setvalues, 'flag': 4})


@login_required
def addBooks(request):
    if (request.method=='POST'):
        form=BookForm(data=request.POST)
        if(form.is_valid()):
            u=UserBooks()
            u.book_name=form.cleaned_data['book_name']
            u.book_author=form.cleaned_data['book_author']
            u.book_ISBN=form.cleaned_data['book_ISBN']
            u.book_status=True
            u.book_genre=form.cleaned_data['book_genre']
            u.username=request.user.username
            u.user_id = User.objects.get(username=request.user.username)
            u.book_url= form.cleaned_data['book_url']
            u.save()
            return redirect('/home')
    else:
        form = BookForm()
    return render (request,'home/addbooks.html',{'form':form})


def favorite_ajax(request):
    data = {'success': False}
    if request.method == 'POST':
        book = request.POST.get('userbooks')
        fav = FavBooks()
        book_id = UserBooks.objects.get(pk=book)
        user_id = request.user
        if(FavBooks.objects.filter(user_id=user_id, book_id=book_id).exists()):
                data['success']=False
                return JsonResponse(data)
        fav.book_id = book_id
        fav.user_id = user_id
        fav.save()
        data['success']=True
    return JsonResponse(data)
def removefavorite_ajax(request):
    data = {'success': False}
    if request.method == 'POST':
        book = request.POST.get('userbooks')
        fav = FavBooks()
        book_id = UserBooks.objects.get(pk=book)
        user_id = request.user
        if(FavBooks.objects.filter(user_id=user_id, book_id=book_id).exists()):
                FavBooks.objects.get(user_id=user_id, book_id=book_id).delete()
                data['success']=True
                return JsonResponse(data)

        data['success']=False
    return JsonResponse(data)

def deleteBook(request):
    if (request.method =='POST'):
        userbook=request.POST['userbook']
        UserBooks.objects.get(pk=userbook).delete()
        return redirect('home:myBooks')

def uploadPic(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            m=form.save(commit=False)
            m.user_id=request.user
            m.save()
            return redirect('home:home')
        else:
            return HttpResponse("validation fails")
    else:
        form = ImageUploadForm()
        return render(request,'home/uploadpic.html',{'form':form})


def UsersBooksView(request,pk):

    obj=get_object_or_404(User,pk=pk)
    return render(request,'home/mybooks.html',{'user':obj})
# Create your views here.

home/templates/home/Base.html
<!DOCTYPE html>
<html lang="en">
    <head>{% block head %}
        <meta charset="UTF-8">
        <title>{% block title %}home{% endblock %}</title>
        {% load staticfiles %}
<link rel="Stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" type='text/css' />
   {% endblock %} </head>

    <body>
        <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class = "navbar-header">
            <a class = "navbar-brand" href="/home">Home</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="/home/myBooks">
                        <span class="glyphicon glyphicon-book"  ></span>&nbsp;
                        Mybooks
                    </a>
                    </li>
                <li class="">
                    <a href="{% url 'home:wishList' %}">
                        <span class="glyphicon glyphicon-heart"  aria-hidden="true"></span>&nbsp;
                        Wishlist
                    </a>
                    </li>

            </ul>
            <form class = "navbar-form navbar-left" role="search" method="get" action="{% url 'home:searchedBooks' %}">{% csrf_token %}
            <div class ="form-group">
                <input type="text" class="form-control" name="q" value="">

          <div class="btn-group">
  <button data-toggle="dropdown" class="btn dropdown-toggle">Search Type <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><input type="radio" id="ID" name="NAME" value="1" checked><label for="ID">Book</label></li>
        <li><input type="radio" id="ID" name="NAME" value="2"><label for="ID">User</label></li>
        <li><input type="radio" id="ID" name="NAME" value="3"><label for="ID">ISBN</label></li>
        <li><input type="radio" id="ID" name="NAME" value="4"><label for="ID">Author</label></li>
      <!-- Other items -->
    </ul>
</div>

                </div>
                <button type="submit" class="btn btn-default">search</button>


            </form>
            <ul class= "nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'home:addBooks' %}">
                         <span class="glyphicon glyphicon-plus"  aria-hidden="true"></span>&nbsp;Add Books
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'logout' %}">
                         <span class="glyphicon glyphicon-off"  aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>

                </ul>
        </div>
    </div>
</nav>

    
      {% block body %}  
     {% endblock %}
    </body>
</html>

home/templates/home/addbooks.html
{% extends 'home/Base.html' %}
{% block title %}Add Books{% endblock %}

{% block body %}

<form class="site-form" action="{% url 'home:addBooks' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">

{% endblock %}

home/templates/home/bookdetails.html
<!DOCTYPE html>

{% extends 'home/Base.html' %}

{% block title %} Book Details {% endblock %}
{% load staticfiles %}

<link rel="stylesheet" href="{{ STATIC_URL }}/home/css/heart.css">
<script src="{% static 'js/heart.css' %}"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="{% static 'js/app.js' %}"></script>

{% block body %}

{% if error_message %}<p><strong> {{ error_message }} </strong></p>{% endif %}
<script type="text/javascript">
$(document).ready(function(){
$("#form_id").on('submit', function(event) {
       event.preventDefault();
       var userbooks = '{{ userbooks.id }}';
       $.ajax({
           type: "POST",
           url: "{% url 'home:favoriteAjax' %}",
           data:{
                 userbooks:userbooks,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
           },
           datatype:'json',
           success: function(data) {
             if (data['success'])
             {
                alert("successfully added to favorites")
                $("form_id1").hide()
                }
             else
                alert("You have already added this to your wish list")
           }
     });
  });
  $("#form_id1").on('submit', function(event) {
       event.preventDefault();
       var userbooks = '{{ userbooks.id }}';
       $.ajax({
           type: "POST",
           url: "{% url 'home:removefavoriteAjax' %}",
           data:{
                 userbooks:userbooks,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
           },
           datatype:'json',
           success: function(data) {
             if (data['success'])
             {
                alert("successfully removed from wishlist")
                $("form_id1").hide()
                }
             else
                alert("You dont have this  in your  wish list")
           }
     });
  });
});

</script>
<div class="container text-center">
  <div class="row">


    <div class="col-sm-3 well">
      <div class="well">
        <p><a href="#">{{ userbooks.book_name }}</a></p>
        <img src="{{ userbooks.book_url }}" class="img-circle" height="65" width="65" alt="Avatar">
      </div>


    </div>
     <div class="col-sm-7">

 <div class="row">
        <div class="col-sm-3">
          <div class="well">
              <p>Book NAME</p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p> {{ userbooks.book_name }}</p><br>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Book AUTHOR</p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
         <p> {{ userbooks.book_author }}</p><br>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
              <p>Book GENRE</p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p> {{ userbooks.book_genre }}</p><br>
          </div>
        </div>
      </div>
         <div class="row">
        <div class="col-sm-3">
          <div class="well">
              <p>Book ISBN</p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p> {{ userbooks.book_ISBN }}</p><br>
          </div>
        </div>
      </div>
         <div class="row">
        <div class="col-sm-3">
          <div class="well">
              <p>Book RATING</p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p> {{ userbooks.book_rating }} </p><br>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p> Book Description </p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
  <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p> Popular Books </p>

          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
              {% for books in popular %}
              {% ifnotequal books userbooks %}
              <a href="/home/{{ books.id }}"><img src="{{ books.book_url }}" class="img-thumbnail" height="65" width="65" alt="Avatar"></a>
                  &nbsp;&nbsp;&nbsp;&nbsp;
              {% endifnotequal %}
              {% endfor %}
          </div>
        </div>
      </div>
    </div>

  </div>
</div>





<form id="form_id" method='post'>{% csrf_token %}
     <button class= "btn btn-success btn-block" type="submit">Favorite</button>
 </form>

{% for fav in favorites %}
{% if fav.book_id == userbooks %}
<form id="form_id1" method='post'>{% csrf_token %}
     <button class="btn btn-success btn-block"  type="submit">Remove from favorites</button>
 </form>
{% endif %}
{% endfor %}

 {% if userbooks in books %}
<form id="form_id2" method='post' action="{% url 'home:deleteBook' %}">{% csrf_token %}
     <input type="hidden" name="userbook" value={{ userbooks.id }}>
     <button class="btn btn-success btn-block" type="submit">Deal Completed</button>
 </form>
{% endif %}


{% endblock %}

home/templates/home/homepage.html
{% extends 'home/Base.html' %}


<head>{% block head %}
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
   <link href="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.css" rel="stylesheet" type="text/css">
<script src="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.js"></script>

  <style>
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
  </style>
{% endblock %}</head>

<body>{% block body %}

<div class="container text-center">
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <p><a href="#">{{ request.user.username }}</a></p>
        {% if flag %}
        <img src="{{ obj.image.url }}" class="img-circle" height="65" width="65" alt="Avatar">
        {% else %}
        <a href="{% url 'home:uploadPic' %}"> UPLOAD PROFILE PICTURE</a>
        {% endif %}
      </div>
      <div class="well">
        <p><a href="#">Genres</a></p>

          {% for bookgenre in bookgenres %}
        {% for key,value in bookgenre.items %}
          <form action="" method="post">{% csrf_token %}
        <button name="topbook" type="submit" value="{{ value }}"><span class="label label-success">{{ value }}</span></button></form>
  {% endfor %}
         {% endfor %}


      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Ey!</strong></p>

      </div>
      <p>contact details</p>
      <p>contact details</p>
      <p>contact details</p>
    </div>
    <div class="col-sm-7">

      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <p contenteditable="true">Status: Feeling Blue</p>
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>
            </div>
          </div>
        </div>
      </div>

      {% for books in topbooks %}
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
          <a class="button" href="/home/{{ books.id }}"> <img src="{{ books.book_url }}" class="img-thumbnail" height="55" width="55" alt="Avatar"></a>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
          <p>{{ books.book_name }}</p>
            <p>{{ books.book_author }}</p>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <h3>Your Books Graph</h3>
         <p>{{ div1|safe }}
            {{ script1|safe }}</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
      <h3>{{ genre }} Graph</h3>
      <p>{{ div|safe }}
            {{ script|safe }}</p>
       </div>


  </div>

</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>


{% endblock %}</body>

home/templates/home/mybooks.html
<!DOCTYPE html>

{% extends 'home/Base.html' %}
{% block title %} User Books {% endblock %}

<head>{% block head %}

  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" type='text/css' />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.css" rel="stylesheet" type="text/css">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.js"></script>

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
  @import url(https://fonts.googleapis.com/css?family=Arvo:700);
@import url(https://fonts.googleapis.com/css?family=Seaweed+Script);

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
    {% endblock %}
</head>
<body>

{% block body %}

{% if error_message %}<p><strong> {{ error_message }} </strong></p>{% endif %}
{{ message }}

<div class="jumbotron">
  <div class="container text-center">
    <h1>Books of {{ user.username }}</h1>

    <p> </p>
  </div>
</div>

<div class="container-fluid bg-3 text-center">
  <div class="row">
      {% for userbooks in user.userbooks_set.all %}
      {% if forloop.counter|divisibleby:4 %}
  </div> <div class="row">
          {% endif %}
    <div class="col-sm-3">
         <a href="/home/{{ userbooks.id }}"> <img src="{{ userbooks.book_url }}" class="img-thumbnail" style="width:30%" alt="{{ userbooks.name }}" height="42" width="42"></a><br><br>
    </div>
      {% endfor %}
</div>


<footer class="container-fluid text-center">


    <p align="right">{{ div|safe }}
            {{ script|safe }} </p>


</footer>

</body>


{% endblock %}

home/templates/home/search.html
{% extends 'home/Base.html' %}
{% block title %} User Books {% endblock %}
<head>{% block head %}

  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" type='text/css' />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
  @import url(https://fonts.googleapis.com/css?family=Arvo:700);
@import url(https://fonts.googleapis.com/css?family=Seaweed+Script);

    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
    {% endblock %}
</head>
{% block body %}

<h1>
    we have found {{ setvalues.count }} results
</h1>
{% if error_message %}<p><strong> {{ error_message }} </strong></p>{% endif %}
    {% for vals in setvalues %}
     {% if flag == 1 or flag == 3 or flag == 4 %}
      <div class="row">
        <div class="col-sm-3">
          <div class="well">



           <p>{{ vals.book_name }}</p>
           <a href="/home/{{ vals.id }}"> <img src="{{ vals.book_url }}" class="img-thumbnail" style="width:10%" alt="{{ vals.book_name }}" height="42" width="42"> </a>
               </div>
            </div>
          <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
           </div>
               {% endif %}



    {% if flag == 2 %}
    <a href="/home/{{ vals.pk }}/userbooks">{{ vals.username }}</a><br>
    {% endif %}
  <br><br>
    {% endfor %}

{% endblock %}

home/templates/home/uploadpic.html
{% extends 'home/Base.html' %}
{% block body %}

<form class="site-form" action="{% url 'home:uploadPic' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
{% endblock %}